server:
  port: 8081
 #This is a service. It has to register itself to eureka server
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761
  
 #database/hibernate specific perporties
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/coursems
    
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
  application:
    name: COURSE-SERVICE
    
    
keycloak:
  realm: courserealm
  auth-server-url: http://localhost:8080
  resource: course-service
  public-client: true
  bearer-only: true